// <auto-generated />
using System;
using InsuranceClaims.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceClaims.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407034831_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsuranceClaims.Models.Entities.Assessment", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentId"));

                    b.Property<decimal>("AssessedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssessmentRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<int>("SurveyorId")
                        .HasColumnType("int");

                    b.HasKey("AssessmentId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("SurveyorId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClaimStatus")
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.HasKey("ClaimId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PolicyId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.ClaimDocument", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("int");

                    b.HasKey("DocumentId");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimDocuments");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.ClaimTracking", b =>
                {
                    b.Property<int>("TrackingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackingId"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TrackingId");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimTrackings");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.FraudCheck", b =>
                {
                    b.Property<int>("FraudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FraudId"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<int>("FraudScore")
                        .HasColumnType("int");

                    b.Property<int>("RiskFlag")
                        .HasColumnType("int");

                    b.HasKey("FraudId");

                    b.HasIndex("ClaimId")
                        .IsUnique();

                    b.ToTable("FraudChecks");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.Officer", b =>
                {
                    b.Property<int>("OfficerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficerId"));

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OfficerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Officers");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<decimal>("CoverageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PolicyId");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.PolicyPurchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PurchaseId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PolicyId");

                    b.ToTable("PolicyPurchases");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.PolicyRenewal", b =>
                {
                    b.Property<int>("RenewalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RenewalId"));

                    b.Property<DateTime>("NewEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RenewalDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RenewalId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PolicyRenewals");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.SettlementLog", b =>
                {
                    b.Property<int>("SettlementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettlementId"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SettlementAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SettlementStatus")
                        .HasColumnType("int");

                    b.HasKey("SettlementId");

                    b.HasIndex("ClaimId")
                        .IsUnique();

                    b.ToTable("SettlementLogs");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.Surveyor", b =>
                {
                    b.Property<int>("SurveyorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurveyorId"));

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SurveyorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Surveyors");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.SurveyorAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfficerId")
                        .HasColumnType("int");

                    b.Property<int>("SurveyorId")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("OfficerId");

                    b.HasIndex("SurveyorId");

                    b.ToTable("SurveyorAssignments");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.Assessment", b =>
                {
                    b.HasOne("InsuranceClaims.Models.Entities.Claim", "Claim")
                        .WithMany("Assessments")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsuranceClaims.Models.Entities.Surveyor", "Surveyor")
                        .WithMany("Assessments")
                        .HasForeignKey("SurveyorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Surveyor");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.Claim", b =>
                {
                    b.HasOne("InsuranceClaims.Models.Entities.Customer", "Customer")
                        .WithMany("Claims")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsuranceClaims.Models.Entities.Policy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.ClaimDocument", b =>
                {
                    b.HasOne("InsuranceClaims.Models.Entities.Claim", "Claim")
                        .WithMany("Documents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.ClaimTracking", b =>
                {
                    b.HasOne("InsuranceClaims.Models.Entities.Claim", "Claim")
                        .WithMany("TrackingHistory")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.Customer", b =>
                {
                    b.HasOne("InsuranceClaims.Models.Entities.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("InsuranceClaims.Models.Entities.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.FraudCheck", b =>
                {
                    b.HasOne("InsuranceClaims.Models.Entities.Claim", "Claim")
                        .WithOne("FraudCheck")
                        .HasForeignKey("InsuranceClaims.Models.Entities.FraudCheck", "ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.Officer", b =>
                {
                    b.HasOne("InsuranceClaims.Models.Entities.User", "User")
                        .WithOne("Officer")
                        .HasForeignKey("InsuranceClaims.Models.Entities.Officer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.PolicyPurchase", b =>
                {
                    b.HasOne("InsuranceClaims.Models.Entities.Customer", "Customer")
                        .WithMany("PolicyPurchases")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsuranceClaims.Models.Entities.Policy", "Policy")
                        .WithMany("PolicyPurchases")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.PolicyRenewal", b =>
                {
                    b.HasOne("InsuranceClaims.Models.Entities.PolicyPurchase", "PolicyPurchase")
                        .WithMany("Renewals")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicyPurchase");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.SettlementLog", b =>
                {
                    b.HasOne("InsuranceClaims.Models.Entities.Claim", "Claim")
                        .WithOne("SettlementLog")
                        .HasForeignKey("InsuranceClaims.Models.Entities.SettlementLog", "ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.Surveyor", b =>
                {
                    b.HasOne("InsuranceClaims.Models.Entities.User", "User")
                        .WithOne("Surveyor")
                        .HasForeignKey("InsuranceClaims.Models.Entities.Surveyor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.SurveyorAssignment", b =>
                {
                    b.HasOne("InsuranceClaims.Models.Entities.Claim", "Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InsuranceClaims.Models.Entities.Officer", "Officer")
                        .WithMany()
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InsuranceClaims.Models.Entities.Surveyor", "Surveyor")
                        .WithMany()
                        .HasForeignKey("SurveyorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Officer");

                    b.Navigation("Surveyor");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.Claim", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Documents");

                    b.Navigation("FraudCheck");

                    b.Navigation("SettlementLog");

                    b.Navigation("TrackingHistory");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.Customer", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("PolicyPurchases");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.Policy", b =>
                {
                    b.Navigation("PolicyPurchases");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.PolicyPurchase", b =>
                {
                    b.Navigation("Renewals");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.Surveyor", b =>
                {
                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("InsuranceClaims.Models.Entities.User", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Officer");

                    b.Navigation("Surveyor");
                });
#pragma warning restore 612, 618
        }
    }
}
